repos:
  - repo: https://github.com/semgrep/semgrep
    rev: '768d0f4c3ccb4b1740eef22bbbd57fc936450df2'  # frozen: v1.84.1
    hooks:
      - id: semgrep
        args:
          - --config
          - 'rules/ p/ci'
          - --error
          - --skip-unknown-extensions
          - --metrics
          - 'off'
        stages:
          - pre-push
  - repo: https://github.com/Yelp/detect-secrets
    rev: '68e8b45440415753fff70a312ece8da92ba85b4a'  # frozen: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline
        stages:
          - pre-commit
        exclude: package-lock.json