name: Detect Secrets Scan

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  detect-secrets:
    name: Detect Secrets Scan
    runs-on: ubuntu-latest
    container:
      image: python:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Change Owner of Container Working Directory
        run: chown root:root .
      - name: Install detect-secrets
        run: pip install detect-secrets
      - name: Run detect-secrets-hook
        shell: bash
        run: |
          git ls-files -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline *
      - name: Show detect-secrets differences
        if: ${{ failure() }}
        run: git diff